### ISSUE TITLE
Better categorization of menu

### ISSUE THREAD

**Issue by nblackburn** [anchorcms/anchor-cms#648]
The navigation system could be better organised to free space where needed. 

> An example of this would be because categories and comments are unique to posts, have a sub menu under posts for them.
### Proposal

An even better solution would be to use PHP's yaml extension and build the navigation based on the following yaml...

> A problem with this method is that i18n would need to be implemented in this file.

``` yaml
posts:
  - categories: {title: Categories, uri: /posts/categories}
  - comments: {title: Comments, uri: /posts/comments}
pages:
users:
  - roles: {title: Posts, uri: users/permissions}
  - permissions: {title: Permissions, uri: /users/permissions}
extend:
  - fields
  - variables
  - meta
  - plugins
```
### Concept

![Example](http://i.imgur.com/L3P9Ink.png)
