### ISSUE TITLE
Feature: change markdown parser & ui improvement & nginx support

### ISSUE THREAD

**Issue by htfy96** [anchorcms/anchor-cms#825]
Hi, 

### Nginx manual
I have successfully installed `anchor ` on a nginx server after searching the forum for configuration (http://forums.anchorcms.com/search?query=nginx). However, the examples on github and anchorcms.com are all based on `apache`, so could you please add a link for nginx configuration? That might be helpful.

### Markdown Parser
In addition, I found that the markdown parser is a 2012 version of `PHP Markdown` which lacks support of many features(e.g \~\~deleted\~\~=~~deleted~~). Then I replaced the default parser with [parsedownExtra](https://github.com/erusev/parsedown). Now it works well with my modified `highlight.js`. Maybe it is better to use this parser.

### Css Improvements
Besides, I also made an improvement to default css:
```css
td { padding: 5px; 12px; }
```
because the default padding of a cell is too narrow.

And the `blockquote` is not defined in css, here is my suggestion:
```css
blockquote
{
    padding-left: 20px;
    border-left: 4px solid #DDD;
    color: #666;
    font-style: italic;
}
```
### Bugs of editor?
When a long passage is typed in the editor, just scroll to the middle and enter a few words, you will find that the line you are editing goes down to the bottom of editor. This is annoying when you are modifying long text. If it is a bug, please fix it.

Thanks for your good work.
